/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sansilvestre.desktop.app.dashboard.screen.component;

/**
 *
 * @author Jan
 */
public class AdministratorMenuComponent extends javax.swing.JPanel {

    /**
     * Creates new form AdministratorMenuComponent
     */
    public AdministratorMenuComponent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scheduleComponent1 = new com.sansilvestre.desktop.app.dashboard.screen.component.ScheduleComponent();
        mainPanelButton = new javax.swing.JButton();
        officesPanelButton = new javax.swing.JButton();
        employeePanelButton = new javax.swing.JButton();
        productsPanelButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(256, 700));

        mainPanelButton.setText("jButton1");

        officesPanelButton.setText("jButton1");

        employeePanelButton.setText("jButton1");

        productsPanelButton.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(scheduleComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productsPanelButton)
                    .addComponent(employeePanelButton)
                    .addComponent(officesPanelButton)
                    .addComponent(mainPanelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scheduleComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainPanelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(officesPanelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeePanelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productsPanelButton)
                .addGap(0, 432, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton employeePanelButton;
    private javax.swing.JButton mainPanelButton;
    private javax.swing.JButton officesPanelButton;
    private javax.swing.JButton productsPanelButton;
    private com.sansilvestre.desktop.app.dashboard.screen.component.ScheduleComponent scheduleComponent1;
    // End of variables declaration//GEN-END:variables
}
