headline = Tiempo sin verte
body = <html><p>Hemos seleccionado tu turno para acceder al panel de ventas ¡Que tengas un excelente día!</p></html>

label.shifts = Horarios
label.login = ¿Tienes una cuenta?

button.open = Vamos
button.login = Sí, quiero ingresar