/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sansilvestre.desktop.app.dashboard.screen;

import com.sansilvestre.desktop.app.dashboard.screen.component.AdministratorMenuComponent;
import com.sansilvestre.desktop.app.product.screen.ProductScreen;
import java.awt.BorderLayout;
import java.awt.Component;

/**
 *
 * @author Jan
 */
public class DashboardScreen extends javax.swing.JPanel {

    private AdministratorMenuComponent adminsMenuComponent = new AdministratorMenuComponent();
    
    private ProductScreen productScreen = new ProductScreen();
    
    /**
     * Creates new form DashboardScreen
     */
    public DashboardScreen() {
        initComponents();
        initScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuSection = new javax.swing.JPanel();
        contentSection = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1200, 700));

        menuSection.setBackground(new java.awt.Color(255, 255, 51));
        menuSection.setPreferredSize(new java.awt.Dimension(256, 700));

        javax.swing.GroupLayout menuSectionLayout = new javax.swing.GroupLayout(menuSection);
        menuSection.setLayout(menuSectionLayout);
        menuSectionLayout.setHorizontalGroup(
            menuSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
        menuSectionLayout.setVerticalGroup(
            menuSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        contentSection.setBackground(new java.awt.Color(255, 255, 51));
        contentSection.setMinimumSize(new java.awt.Dimension(944, 700));
        contentSection.setPreferredSize(new java.awt.Dimension(944, 700));

        javax.swing.GroupLayout contentSectionLayout = new javax.swing.GroupLayout(contentSection);
        contentSection.setLayout(contentSectionLayout);
        contentSectionLayout.setHorizontalGroup(
            contentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentSectionLayout.setVerticalGroup(
            contentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initScreen() {
        insertMenu(adminsMenuComponent);
        insertContent(productScreen);
    }
    
    private void insertMenu(Component menu) {
        menu.setSize(256, 700);
        menu.setLocation(0, 0);
        menuSection.removeAll();
        menuSection.add(menu, new BorderLayout());
        menuSection.revalidate();
        menuSection.repaint();
    }

    private void insertContent(Component content) {
        content.setSize(944, 700);
        content.setLocation(0, 0);
        contentSection.removeAll();
        contentSection.add(content);
        contentSection.revalidate();
        contentSection.repaint();
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentSection;
    private javax.swing.JPanel menuSection;
    // End of variables declaration//GEN-END:variables
}