package com.sansilvestre.desktop.app.product.main.screen;

import com.formdev.flatlaf.FlatClientProperties;
import com.sansilvestre.desktop.app.AppStrings;
import com.sansilvestre.desktop.app.Theme;
import com.sansilvestre.desktop.app.dashboard.util.KeyBinds;
import com.sansilvestre.desktop.app.product.add.AddProductWindow;
import com.sansilvestre.desktop.app.product.main.data.mapper.ProductMapper;
import com.sansilvestre.desktop.app.product.main.domain.model.ProductTableModel;
import com.sansilvestre.desktop.app.product.main.domain.model.ProductTableModelList;
import com.sansilvestre.desktop.app.product.main.module.ProductModule;
import com.sansilvestre.desktop.app.product.domain.model.Product;
import com.sansilvestre.desktop.app.product.screen.resource.ProductStrings;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.List;

public class ProductFragment extends javax.swing.JPanel implements ProductState {

    private final ProductViewModel viewModel = ProductModule.getInstance().provideProductViewModel();

    public ProductFragment() {
        initComponents();
        stylizeComponents();
        initUIStyles();
        setup();
        seachInput.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    seachInput.setText("");
                    KeyBinds.getInstance().restartKeyBindsService();
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
                if (seachInput.getText() != "") {
                    viewModel.onEvent(new ProductEvent.GetProductWithQuery(seachInput.getText()));
                } else {
                    viewModel.onEvent(new ProductEvent.GetProductList());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headline = new javax.swing.JLabel();
        body = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productList = new javax.swing.JTable();
        seachInput = new javax.swing.JTextField();
        activeFilter = new javax.swing.JComboBox<>();
        categoryFilter = new javax.swing.JComboBox<>();
        officeFilter = new javax.swing.JComboBox<>();
        productDetailsConteiner = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        barcodeLabel = new javax.swing.JLabel();
        barcode = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();
        addedDateLabel = new javax.swing.JLabel();
        addedDate = new javax.swing.JLabel();
        updatedDateLabel = new javax.swing.JLabel();
        updatedDate = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        profit = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        roundedPrice = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(768, 640));

        headline.setText("Headline");

        body.setText("Body");

        addButton.setText("jButton1");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        productList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock", "Producto", "Codigo de Barras", "Precio C.", "Precio V.", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(productList);
        if (productList.getColumnModel().getColumnCount() > 0) {
            productList.getColumnModel().getColumn(0).setMinWidth(64);
            productList.getColumnModel().getColumn(0).setPreferredWidth(64);
            productList.getColumnModel().getColumn(0).setMaxWidth(64);
            productList.getColumnModel().getColumn(1).setMinWidth(128);
            productList.getColumnModel().getColumn(1).setPreferredWidth(256);
            productList.getColumnModel().getColumn(2).setMinWidth(128);
            productList.getColumnModel().getColumn(2).setPreferredWidth(128);
            productList.getColumnModel().getColumn(2).setMaxWidth(128);
            productList.getColumnModel().getColumn(3).setMinWidth(64);
            productList.getColumnModel().getColumn(3).setPreferredWidth(64);
            productList.getColumnModel().getColumn(3).setMaxWidth(64);
            productList.getColumnModel().getColumn(4).setMinWidth(64);
            productList.getColumnModel().getColumn(4).setPreferredWidth(64);
            productList.getColumnModel().getColumn(4).setMaxWidth(64);
            productList.getColumnModel().getColumn(5).setMinWidth(128);
            productList.getColumnModel().getColumn(5).setPreferredWidth(128);
            productList.getColumnModel().getColumn(5).setMaxWidth(128);
        }

        seachInput.setText("jTextField1");
        seachInput.setPreferredSize(new java.awt.Dimension(160, 22));

        activeFilter.setEditable(true);
        activeFilter.setPreferredSize(new java.awt.Dimension(96, 22));

        categoryFilter.setEditable(true);
        categoryFilter.setPreferredSize(new java.awt.Dimension(160, 22));

        officeFilter.setEditable(true);
        officeFilter.setPreferredSize(new java.awt.Dimension(160, 22));

        productDetailsConteiner.setPreferredSize(new java.awt.Dimension(59, 128));

        name.setText("Label");

        barcodeLabel.setText("Barcode");

        barcode.setText("0XXXXXXXXX");

        categoryLabel.setText("Category");

        category.setText("Healt");

        stockLabel.setText("Stock");

        stock.setText("0");

        addedDateLabel.setText("jLabel8");

        addedDate.setText("jLabel9");

        updatedDateLabel.setText("jLabel10");

        updatedDate.setText("jLabel11");

        cost.setText("jLabel1");

        profit.setText("jLabel4");

        price.setText("jLabel5");

        roundedPrice.setText("jLabel7");

        updateButton.setText("jButton1");
        updateButton.setMaximumSize(new java.awt.Dimension(128, 23));
        updateButton.setMinimumSize(new java.awt.Dimension(128, 23));
        updateButton.setPreferredSize(new java.awt.Dimension(128, 23));

        deleteButton.setText("jButton3");
        deleteButton.setMaximumSize(new java.awt.Dimension(128, 23));
        deleteButton.setMinimumSize(new java.awt.Dimension(128, 23));
        deleteButton.setPreferredSize(new java.awt.Dimension(128, 23));

        javax.swing.GroupLayout productDetailsConteinerLayout = new javax.swing.GroupLayout(productDetailsConteiner);
        productDetailsConteiner.setLayout(productDetailsConteinerLayout);
        productDetailsConteinerLayout.setHorizontalGroup(
            productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productDetailsConteinerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addGroup(productDetailsConteinerLayout.createSequentialGroup()
                        .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barcodeLabel)
                            .addComponent(barcode))
                        .addGap(24, 24, 24)
                        .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryLabel)
                            .addComponent(category))
                        .addGap(24, 24, 24)
                        .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockLabel)
                            .addComponent(stock))
                        .addGap(24, 24, 24)
                        .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addedDateLabel)
                            .addComponent(addedDate))
                        .addGap(24, 24, 24)
                        .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updatedDateLabel)
                            .addComponent(updatedDate))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cost)
                    .addComponent(roundedPrice)
                    .addComponent(price)
                    .addComponent(profit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        productDetailsConteinerLayout.setVerticalGroup(
            productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productDetailsConteinerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(cost)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productDetailsConteinerLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barcodeLabel)
                            .addComponent(categoryLabel)
                            .addComponent(stockLabel)
                            .addComponent(addedDateLabel)
                            .addComponent(updatedDateLabel))
                        .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(productDetailsConteinerLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(barcode)
                                    .addComponent(category)
                                    .addComponent(stock)
                                    .addComponent(addedDate)
                                    .addComponent(updatedDate)))
                            .addGroup(productDetailsConteinerLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(productDetailsConteinerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roundedPrice)))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(body)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(productDetailsConteiner, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(headline)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(seachInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(activeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoryFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(officeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addButton)))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(headline)
                .addGap(4, 4, 4)
                .addComponent(body)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activeFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(officeFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addButton))
                    .addComponent(seachInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(productDetailsConteiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stylizeComponents() {
        stylizeHeadline();
        stylizeBody();
        stylizeSearchField();
        stylizeAddButton();
        stylizeTable();
        stylizeProductDetailsConteiner();
        stylizeProductLabel();
        stylizeBardcodeSection();
        stylizeCategorySection();
        stylizeStockSection();
        stylizeAddedDateSection();
        stylizeUpdatedDateSection();
        stylizeUpdatePriceButton();
    }

    private void stylizeHeadline() {
        headline.putClientProperty(FlatClientProperties.STYLE, Theme.applySectionStyle());
        headline.setText(ProductStrings.getSection());
    }

    private void stylizeBody() {
        body.putClientProperty(FlatClientProperties.STYLE, Theme.applyBodyStyle());
        body.setText(ProductStrings.getSentence());
    }

    private void stylizeSearchField() {
        seachInput.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, ProductStrings.getSearchPlaceholder());
        seachInput.setText(AppStrings.getDefaultText());
    }

    private void stylizeAddButton() {
        addButton.setText(AppStrings.getAddButton());
    }

    private void stylizeTable() {
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);
        productList.getColumnModel().getColumn(0).setCellRenderer(center);
        productList.getColumnModel().getColumn(2).setCellRenderer(center);
        productList.getColumnModel().getColumn(5).setCellRenderer(center);
    }

    private void stylizeProductDetailsConteiner() {
        productDetailsConteiner.putClientProperty(FlatClientProperties.STYLE, Theme.applyConteinerStyle());
    }

    private void stylizeProductLabel() {
        name.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelLargeStyle());
    }

    private void stylizeBardcodeSection() {
        barcodeLabel.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelSmallStyle());
        barcode.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelMediumStyle());
    }

    private void stylizeCategorySection() {
        categoryLabel.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelSmallStyle());
        category.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelMediumStyle());
    }

    private void stylizeStockSection() {
        stockLabel.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelSmallStyle());
        stock.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelMediumStyle());
    }

    private void stylizeAddedDateSection() {
        addedDateLabel.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelSmallStyle());
        addedDate.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelMediumStyle());
    }

    private void stylizeUpdatedDateSection() {
        addedDateLabel.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelSmallStyle());
        addedDate.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelMediumStyle());
    }

    private void stylizeUpdatePriceButton() {
        deleteButton.putClientProperty(FlatClientProperties.STYLE, Theme.applyDefaultStyle());
        deleteButton.setText(ProductStrings.getUpdatePriceButton());
    }

    private void setup() {
        viewModel.setState(this);
        init();
    }

    private void init() {
        viewModel.onEvent(new ProductEvent.GetProductList());
        activeFilter.addItem(ProductStrings.getActiveItemFilter());
        activeFilter.addItem(ProductStrings.getInactiveItemFilter());
        categoryFilter.addItem(ProductStrings.getCategoryItemFilter());
        officeFilter.addItem(ProductStrings.getOfficeItemFilter());
    }

    private void initProductDetailsSection(ProductTableModel product) {
        name.setText(product.getName());
        barcode.setText(product.getBarcode());
        category.setText(product.getCategory());
        stock.setText(product.getStock());
    }

    @Override
    public void onGetProductList(List<ProductTableModel> list) {
        DefaultTableModel model = (DefaultTableModel) productList.getModel();
        model.setRowCount(0);
        initProductDetailsSection(list.getFirst());
        for (ProductTableModel product: list) {
            model.addRow(ProductMapper.toObject(product));
        }
    }

    @Override
    public void onProductSelected(ProductTableModel data) {
        onItemSelectedList();
    }

    private void onItemSelectedList() {
        ListSelectionModel listSelectionModel = productList.getSelectionModel();
        listSelectionModel.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = productList.getSelectedRow();
                if (selectedRow != -1) {
                    // Row is selected, do something
                    name.setText(productList.getValueAt(selectedRow, 2).toString());
                }
            }
        });
    }

    private void initUIStyles() {
        //jPanel1.putClientProperty(FlatClientProperties.STYLE, Theme.applyConteinerStyle());
        jScrollPane1.putClientProperty(FlatClientProperties.STYLE, Theme.applyDefaultStyle());
        productList.putClientProperty(FlatClientProperties.STYLE, Theme.applyDefaultStyle());
    }
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        AddProductWindow.getInstance().invoke();
        KeyBinds.getInstance().restartKeyBindsService();
    }//GEN-LAST:event_addButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> activeFilter;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addedDate;
    private javax.swing.JLabel addedDateLabel;
    private javax.swing.JLabel barcode;
    private javax.swing.JLabel barcodeLabel;
    private javax.swing.JLabel body;
    private javax.swing.JLabel category;
    private javax.swing.JComboBox<String> categoryFilter;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel cost;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel headline;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JComboBox<String> officeFilter;
    private javax.swing.JLabel price;
    private javax.swing.JPanel productDetailsConteiner;
    private javax.swing.JTable productList;
    private javax.swing.JLabel profit;
    private javax.swing.JLabel roundedPrice;
    private javax.swing.JTextField seachInput;
    private javax.swing.JLabel stock;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel updatedDate;
    private javax.swing.JLabel updatedDateLabel;
    // End of variables declaration//GEN-END:variables
}
