package com.sansilvestre.desktop.app.product.main.screen;

import com.formdev.flatlaf.FlatClientProperties;
import com.sansilvestre.desktop.app.AppStrings;
import com.sansilvestre.desktop.app.Theme;
import com.sansilvestre.desktop.app.dashboard.util.KeyBinds;
import com.sansilvestre.desktop.app.product.create.NewProductWindow;
import com.sansilvestre.desktop.app.product.create.domain.util.Currency;
import com.sansilvestre.desktop.app.product.main.module.ProductModule;
import com.sansilvestre.desktop.app.product.domain.model.Product;
import com.sansilvestre.desktop.app.product.screen.resource.ProductStrings;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.List;

public class ProductFragment extends javax.swing.JPanel implements ProductState {

    private final ProductViewModel viewModel = ProductModule.getInstance().provideProductViewModel();

    public ProductFragment() {
        initComponents();
        stylizeComponents();
        initUIStyles();
        setup();
        seachInput.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    seachInput.setText("");
                    KeyBinds.getInstance().restartKeyBindsService();
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
                viewModel.onEvent(new ProductEvent.SearchProduct(seachInput.getText()));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headline = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productList = new javax.swing.JTable();
        seachInput = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        productDetailsConteiner = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        barcodeLabel = new javax.swing.JLabel();
        barcode = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();
        addedDateLabel = new javax.swing.JLabel();
        addedDate = new javax.swing.JLabel();
        updatedDateLabel = new javax.swing.JLabel();
        updatedDate = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        profit = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        roundedPrice = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        updateStockButton = new javax.swing.JButton();
        updatePriceButton = new javax.swing.JButton();

        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(768, 640));

        headline.setText("section");

        addButton.setText("jButton1");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("jButton1");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        productList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Stock", "Producto", "Codigo de Barras", "Precio C.", "Precio V.", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(productList);
        if (productList.getColumnModel().getColumnCount() > 0) {
            productList.getColumnModel().getColumn(0).setMinWidth(40);
            productList.getColumnModel().getColumn(0).setPreferredWidth(40);
            productList.getColumnModel().getColumn(0).setMaxWidth(40);
            productList.getColumnModel().getColumn(1).setMinWidth(64);
            productList.getColumnModel().getColumn(1).setPreferredWidth(64);
            productList.getColumnModel().getColumn(1).setMaxWidth(64);
            productList.getColumnModel().getColumn(2).setMinWidth(128);
            productList.getColumnModel().getColumn(2).setPreferredWidth(256);
            productList.getColumnModel().getColumn(3).setMinWidth(128);
            productList.getColumnModel().getColumn(3).setPreferredWidth(128);
            productList.getColumnModel().getColumn(3).setMaxWidth(128);
            productList.getColumnModel().getColumn(4).setMinWidth(64);
            productList.getColumnModel().getColumn(4).setPreferredWidth(64);
            productList.getColumnModel().getColumn(4).setMaxWidth(64);
            productList.getColumnModel().getColumn(5).setMinWidth(64);
            productList.getColumnModel().getColumn(5).setPreferredWidth(64);
            productList.getColumnModel().getColumn(5).setMaxWidth(64);
            productList.getColumnModel().getColumn(6).setMinWidth(128);
            productList.getColumnModel().getColumn(6).setPreferredWidth(128);
            productList.getColumnModel().getColumn(6).setMaxWidth(128);
        }

        seachInput.setText("jTextField1");
        seachInput.setPreferredSize(new java.awt.Dimension(192, 22));

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setEditable(true);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setEditable(true);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        productDetailsConteiner.setPreferredSize(new java.awt.Dimension(59, 128));

        name.setText("Label");

        barcodeLabel.setText("Barcode");

        barcode.setText("0XXXXXXXXX");

        categoryLabel.setText("Category");

        category.setText("Healt");

        stockLabel.setText("Stock");

        stock.setText("0");

        addedDateLabel.setText("jLabel8");

        addedDate.setText("jLabel9");

        updatedDateLabel.setText("jLabel10");

        updatedDate.setText("jLabel11");

        cost.setText("jLabel1");

        profit.setText("jLabel4");

        price.setText("jLabel5");

        roundedPrice.setText("jLabel7");

        updateButton.setText("jButton1");
        updateButton.setMaximumSize(new java.awt.Dimension(128, 23));
        updateButton.setMinimumSize(new java.awt.Dimension(128, 23));
        updateButton.setPreferredSize(new java.awt.Dimension(128, 23));

        updateStockButton.setText("jButton2");
        updateStockButton.setMaximumSize(new java.awt.Dimension(128, 23));
        updateStockButton.setMinimumSize(new java.awt.Dimension(128, 23));
        updateStockButton.setPreferredSize(new java.awt.Dimension(128, 23));

        updatePriceButton.setText("jButton3");
        updatePriceButton.setMaximumSize(new java.awt.Dimension(128, 23));
        updatePriceButton.setMinimumSize(new java.awt.Dimension(128, 23));
        updatePriceButton.setPreferredSize(new java.awt.Dimension(128, 23));

        javax.swing.GroupLayout productDetailsConteinerLayout = new javax.swing.GroupLayout(productDetailsConteiner);
        productDetailsConteiner.setLayout(productDetailsConteinerLayout);
        productDetailsConteinerLayout.setHorizontalGroup(
            productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productDetailsConteinerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addGroup(productDetailsConteinerLayout.createSequentialGroup()
                        .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barcodeLabel)
                            .addComponent(barcode))
                        .addGap(24, 24, 24)
                        .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryLabel)
                            .addComponent(category))
                        .addGap(24, 24, 24)
                        .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockLabel)
                            .addComponent(stock))
                        .addGap(24, 24, 24)
                        .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addedDateLabel)
                            .addComponent(addedDate))
                        .addGap(24, 24, 24)
                        .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updatedDateLabel)
                            .addComponent(updatedDate))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cost)
                    .addComponent(roundedPrice)
                    .addComponent(price)
                    .addComponent(profit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateStockButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePriceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        productDetailsConteinerLayout.setVerticalGroup(
            productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productDetailsConteinerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(cost)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productDetailsConteinerLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barcodeLabel)
                            .addComponent(categoryLabel)
                            .addComponent(stockLabel)
                            .addComponent(addedDateLabel)
                            .addComponent(updatedDateLabel)
                            .addComponent(updateStockButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(productDetailsConteinerLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(productDetailsConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(barcode)
                                    .addComponent(category)
                                    .addComponent(stock)
                                    .addComponent(addedDate)
                                    .addComponent(updatedDate)))
                            .addGroup(productDetailsConteinerLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(updatePriceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(productDetailsConteinerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roundedPrice)))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productDetailsConteiner, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(headline)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(seachInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(headline)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(deleteButton)
                    .addComponent(seachInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(productDetailsConteiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stylizeComponents() {
        stylizeHeadline();
        stylizeSearchField();
        stylizeAddButton();
        stylizeDeleteButton();
        stylizeTable();
        stylizeProductDetailsConteiner();
        stylizeProductLabel();
        stylizeBardcodeSection();
        stylizeCategorySection();
        stylizeStockSection();
        stylizeAddedDateSection();
        stylizeUpdatedDateSection();
        stylizeUpdateStockButton();
        stylizeUpdatePriceButton();
    }

    private void stylizeHeadline() {
        headline.putClientProperty(FlatClientProperties.STYLE, Theme.applySectionStyle());
        headline.setText(ProductStrings.getSection());
    }

    private void stylizeSearchField() {
        seachInput.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, ProductStrings.getSearchPlaceholder());
        seachInput.setText(AppStrings.getDefaultText());
    }

    private void stylizeAddButton() {
        addButton.setText(AppStrings.getAddButton());
    }

    private void stylizeDeleteButton() {
        deleteButton.putClientProperty(FlatClientProperties.STYLE, Theme.applyDeleteButtonStyle());
        deleteButton.setText(AppStrings.getDeleteButton());
    }

    private void stylizeTable() {
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);
        productList.getColumnModel().getColumn(1).setCellRenderer(center);
        productList.getColumnModel().getColumn(3).setCellRenderer(center);
        productList.getColumnModel().getColumn(6).setCellRenderer(center);
    }

    private void stylizeProductDetailsConteiner() {
        productDetailsConteiner.putClientProperty(FlatClientProperties.STYLE, Theme.applyConteinerStyle());
    }

    private void stylizeProductLabel() {
        name.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelLargeStyle());
    }

    private void stylizeBardcodeSection() {
        barcodeLabel.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelSmallStyle());
        barcode.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelMediumStyle());
    }

    private void stylizeCategorySection() {
        categoryLabel.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelSmallStyle());
        category.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelMediumStyle());
    }

    private void stylizeStockSection() {
        stockLabel.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelSmallStyle());
        stock.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelMediumStyle());
    }

    private void stylizeAddedDateSection() {
        addedDateLabel.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelSmallStyle());
        addedDate.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelMediumStyle());
    }

    private void stylizeUpdatedDateSection() {
        addedDateLabel.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelSmallStyle());
        addedDate.putClientProperty(FlatClientProperties.STYLE, Theme.applyLabelMediumStyle());
    }

    private void stylizeUpdateStockButton() {
        updateStockButton.putClientProperty(FlatClientProperties.STYLE, Theme.applyDefaultStyle());
        updateStockButton.setText(ProductStrings.getUpdateStockButton());
    }

    private void stylizeUpdatePriceButton() {
        updatePriceButton.putClientProperty(FlatClientProperties.STYLE, Theme.applyDefaultStyle());
        updatePriceButton.setText(ProductStrings.getUpdatePriceButton());
    }

    private void setup() {
        initUIController();
        onItemSelectedList();
    }

    private void initUIController() {
        viewModel.setState(this);
        viewModel.onEvent(new ProductEvent.GetProductList());
    }

    @Override
    public void fetchProductList(List<Product> list) {
        DefaultTableModel model = (DefaultTableModel) productList.getModel();
        model.setRowCount(0);
        for (Product product: list) {
            model.addRow(new Object[] {
                    false,
                    product.getStock(),
                    product.getLabel(),
                    product.getBarcode(),
                    Currency.format(product.getCost()),
                    123.2,
                    product.getCategory().getValue()
            });
        }
    }

    private void onItemSelectedList() {
        ListSelectionModel listSelectionModel = productList.getSelectionModel();
        listSelectionModel.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = productList.getSelectedRow();
                if (selectedRow != -1) {
                    // Row is selected, do something
                    name.setText(productList.getValueAt(selectedRow, 2).toString());
                }
            }
        });
    }

    private void initUIStyles() {
        //jPanel1.putClientProperty(FlatClientProperties.STYLE, Theme.applyConteinerStyle());
        jScrollPane1.putClientProperty(FlatClientProperties.STYLE, Theme.applyDefaultStyle());
        productList.putClientProperty(FlatClientProperties.STYLE, Theme.applyDefaultStyle());
    }
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        NewProductWindow.getInstance().invoke();
        KeyBinds.getInstance().restartKeyBindsService();
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        KeyBinds.getInstance().restartKeyBindsService();
    }//GEN-LAST:event_deleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addedDate;
    private javax.swing.JLabel addedDateLabel;
    private javax.swing.JLabel barcode;
    private javax.swing.JLabel barcodeLabel;
    private javax.swing.JLabel category;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel cost;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel headline;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel price;
    private javax.swing.JPanel productDetailsConteiner;
    private javax.swing.JTable productList;
    private javax.swing.JLabel profit;
    private javax.swing.JLabel roundedPrice;
    private javax.swing.JTextField seachInput;
    private javax.swing.JLabel stock;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updatePriceButton;
    private javax.swing.JButton updateStockButton;
    private javax.swing.JLabel updatedDate;
    private javax.swing.JLabel updatedDateLabel;
    // End of variables declaration//GEN-END:variables
}
