#
# Silvestry Custom Components
#
# This color palette is based on Google's material design 3. For more information you can consult
# https://m3.material.io/
#
# The official software documentation will be available later in this repository.
#
# For more information about the color palette you can see the files FlatLightLaf/FlatDarkLaf.properties
#
logo = \
  [light]foreground:#45483D; \
  [dark]foreground:#C5C8B9; \
  font:bold +2

headline = \
  [light]foreground:#4F6628; \
  [dark]foreground:#B5D086; \
  font:bold +20

headline.large = \
  font:bold +20

headline.medium = \
  font:bold +16

headline.small = \
  font:bold +12

title.large = \
  font:bold +10

title.medium = \
  font:bold +8

title.small = \
  font:bold +9

titleSmall = \
  font:bold +10

label.large = \
  font:bold +6

label.medium = \
  font:bold +3

label.small = \
  font:bold


body.large.variant = \
    font:plain +6; \
    [light]foreground:#45483D; \
    [dark]foreground:#C5C8B9

body.medium = \
  font:plain +3


body.medium.variant = \
    font:plain +3; \
    [light]foreground:#45483D; \
    [dark]foreground:#C5C8B9

body.small = \
  font:plain

labelMedium = \
  font:plain +2

labelLarge = \
  font:bold +6

section = \
  font:bold +20

bodySmallVariant = \
  [light]foreground:#45483D; \
  [dark]foreground:#C5C8B9

bodyLarge = \
  font:plain +4

body = \
  [light]foreground:#1A1C15; \
  [dark]foreground:#E3E3D8

supportingText = \
  [light]foreground:#45483D; \
  [dark]foreground:#C5C8B9

field.plain = \
  [light]background:#596248; \
  [dark]background:#1E2019; \
  [light]foreground:#FFFFFF; \
  [dark]foreground:#E3E3D8

combo.box.variant = \
  [light]background:#596248; \
  [dark]editableBackground:#1E2019; \
  [light]foreground:#FFFFFF; \
  [dark]foreground:#E3E3D8; \
  [dark]buttonBackground:#1E2019; \
  [dark]popupBackground:#1A1C15

field.outline = \
  [light]background:#596248; \
  [dark]background:#12140E; \
  [light]foreground:#FFFFFF; \
  [dark]foreground:#E3E3D8; \
  [dark]borderColor:#1E2019; \
  borderWidth:1

secondaryButton = \
  [light]background:#596248; \
  [dark]background:#414A32; \
  [light]foreground:#FFFFFF; \
  [dark]foreground:#DDE6C6

supportingButton = \
  [light]foreground:#4F6628; \
  [dark]foreground:#B5D086; \
  border:3, 3, 3, 3

deleteButton = \
  [light]background:#BA1A1A; \
  [light]foreground:#FFFFFF; \
  [dark]background:#93000A; \
  [dark]foreground:#FFDAD6

container = \
  [light]background:#E3E3D8; \
  [dark]background:#1A1C15; \
  arc:8

container.variant = \
  [light]background:#E3E3D8; \
  [dark]background:#0D0F09; \
  arc:32

button.secondary = \
  [light]foreground:#4F6628; \
  [dark]background:#414A32; \
  [dark]foreground:#DDE6C6

button.outline = \
  [light]foreground:#4F6628; \
  [dark]background:#1A1C15; \
  [dark]hoverBackground:#1B230D; \
  [dark]foreground:#B5D086; \
  [dark]borderColor:#B5D086; \
  [dark]hoverBorderColor:#D1ECA0; \
  [dark]focusColor:#B5D086; \
  borderWidth:0.5; \
  innerFocusWidth:0.1;
# Color inventado: 2E1D1B
button.outline.danger = \
  [light]foreground:#4F6628; \
  [dark]background:#1A1C15; \
  [dark]hoverBackground:#2E1D1B; \
  [dark]foreground:#FFB4AB; \
  [dark]borderColor:#FFB4AB; \
  [dark]hoverBorderColor:#FFDAD6; \
  [dark]focusColor:#FFB4AB; \
  borderWidth:0.5; \
  innerFocusWidth:0.1;

button.text = \
  [light]foreground:#4F6628; \
  [dark]foreground:#B5D086; \
  border:4, 6, 4, 6

button.menu = \
  [light]foreground:#4F6628; \
  [dark]background:#12140E; \
  [dark]foreground:#E3E3D8; \
  [dark]focusColor:#12140E; \
  margin:8, 12, 8, 12; \
  arc:8; \
  font:bold

button.menu.active = \
  [light]foreground:#4F6628; \
  [dark]background:#12140E; \
  [dark]hoverBackground:#1B230D; \
  [dark]foreground:#B5D086; \
  [dark]borderColor:#B5D086; \
  [dark]hoverBorderColor:#D1ECA0; \
  [dark]focusColor:#B5D086; \
  margin:8, 12, 8, 12; \
  arc:8; \
  borderWidth:0.5; \
  innerFocusWidth:0.1; \
  font:bold

button.group = \
  [light]foreground:#4F6628; \
  [dark]background:#1E2019; \
  [dark]hoverBackground:#292B23; \
  [dark]foreground:#E3E3D8; \
  [dark]borderColor:#33362E; \
  [dark]hoverBorderColor:#33362E; \
  [dark]focusColor:#33362E; \
  margin:6, 12, 6, 12; \
  arc:8; \
  borderWidth:0.5; \
  innerFocusWidth:0.1