app.name = Silvestry

button.login = Iniciar Sesión

button.add = Nuevo
button.update = Editar
button.delete = Eliminar
delete.other = Más

button.accept = Aceptar
button.cancel = Cancelar
button.back = Volver

button.open = Abrir
button.close = Cerrar
button.change = Cambiar de Caja

finishButton = Finalizar
goBackButton = Volver