label.headline = Silvestry
label.body = Disfruta de nuestra jornada con nosotros

input.search.placeholder = 0XXXXXXYYYYYY

label.name = Producto
label.amount = Cantidad

label.detail = Transacción
label.sale = Venta
label.checkout = Caja
label.date = Fecha y Hora
label.total = Total

label.employee = Empleados

button.delete = Quitar Item

button.collect = Cobrar
button.cancel = Cancelar