#
# Product Fragment texts in Spanish
#
headline = Nuevo Producto

officeLabel = Local
dateLabel = Fecha

productLabel = Producto
productPlaceholder = Descripción
barcodeLabel = Codigo de Barras
barcodePlaceholder = 0XXXXXXXXX
categoryLabel = Categoria
purchaseCostLabel = Precio C./Unidad
purchaseCostPlaceholder = $ 0,00
stockLabel = Stock
stockPlaceholder = 0
taxLabel = IVA 21%
basePriceLabel = Precio C.
utilitiesLabel = Utilidades
finalPriceLabel = Venta