#
# Light Theme by JannStylz
#
# This color palette is based on Google's material design 3. For more information you can consult
# https://m3.material.io/
#
# The official software documentation will be available later in this repository.
#
# This interface is based on the design system provided by FlatLaf,
# which is modified to adapt it to the Silvestry system.
#
# Color Palette
# #4F6628: Primary
# #FFFFFF: On Primary
# #D1ECA0: Primary Conteiner
# #131F00: On Primary Conteiner
# #FAFAEE: Surface
# #1A1C15: On Surface
# #E2E4D4: Surface Variant
# #45483D: On Surface Variant
# #E3E3D8: Surface Conteiner Highest
# #EEEFE3: Surface Conteiner
#
# Font
# Roboto, REGULAR, 16
#
@background:#FAFAEE
@accentColor:#4F6628

TitlePane.background = #FAFAEE

Label.foreground = #1A1C15

TextField.background = #E3E3D8
TextField.foreground = #1A1C15
TextField.placeHolderForeground = #45483D

PasswordField.background = #E3E3D8
PasswordField.foreground = #1A1C15
PasswordField.showRevealButton = true

FormattedTextField.background = #E3E3D8
FormattedTextField.foreground = #1A1C15

Spinner.background = #E3E3D8
Spinner.foreground = #1A1C15
Spinner.buttonBackground = #E3E3D8
Spinner.buttonSeparatorColor = null
Spinner.buttonStyle = none

Button.background = #4F6628
Button.foreground = #FFFFFF

ComboBox.editableBackground = #E3E3D8
ComboBox.foreground = #1A1C15
ComboBox.popupBackground = #EEEFE3

ComboBox.buttonBackground = #E3E3D8
ComboBox.buttonEditableBackground = #45483D
ComboBox.buttonArrowColor = #45483D

PopupMenu.background = #EEEFE3
PopupMenu.borderColor = #EEEFE3
PopupMenu.borderCornerRadius = 4

MenuItem.selectionBackground = #E3E3D8
MenuItem.selectionForeground = #1A1C15
MenuItem.selectionArc = 4

TableHeader.background = #E3E3D8
TableHeader.foreground = #1A1C15
TableHeader.separatorColor = #E3E3D8
TableHeader.sortIconColor = #1A1C15

Table.background = #E3E3D8
Table.foreground = #1A1C15
Table.selectionBackground = #E2E4D4
Table.selectionForeground = #1A1C15
Table.selectionInactiveBackground = #EEEFE3
Table.selectionInactiveForeground = #1A1C15