#
# Dark Palette by JannStylz
#
# This color palette is based on Google's material design 3. For more information you can consult
# https://m3.material.io/
#
# The official software documentation will be available later in this repository.
#
# This interface is based on the design system provided by FlatLaf,
# which is modified to adapt it to the Silvestry system.
#
# Color Palette
# #B5D086: Primary
# #233600: On Primary
# #12140E: Surface
# #E3E3D8: On Surface
# #C5C8B9: On Surface Variant
# #33362E: Surface Conteiner Highest
# #1E2019: Surface Conteiner
#
# Font
# Roboto, REGULAR, 16
#
@background:#12140E
@accentColor:#B5D086

TitlePane.background = #12140E

Panel.background = #12140E

Label.foreground = #E3E3D8

TextField.background = #33362E
TextField.foreground = #E3E3D8
TextField.selectionBackground = #33362E
TextField.placeHolderForeground = #C5C8B9

PasswordField.background = #33362E
PasswordField.foreground = #E3E3D8
PasswordField.showRevealButton = true

FormattedTextField.background = #33362E
FormattedTextField.foreground = #E3E3D8

Spinner.background = #33362E
Spinner.foreground = #E3E3D8
Spinner.buttonBackground = #33362E
Spinner.buttonSeparatorColor = null
Spinner.buttonStyle = none

Button.background = #B5D086
Button.foreground = #233600

ComboBox.editableBackground = #33362E
ComboBox.foreground = #E3E3D8
ComboBox.popupBackground = #1E2019

ComboBox.buttonBackground = #33362E
ComboBox.buttonEditableBackground = #C5C8B9
ComboBox.buttonArrowColor = #C5C8B9

PopupMenu.background = #1E2019
PopupMenu.borderColor = #1E2019
PopupMenu.borderCornerRadius = 4

MenuItem.selectionBackground = #33362E
MenuItem.selectionForeground = #E3E3D8
MenuItem.selectionArc = 4

TableHeader.background = #1A1C15
TableHeader.foreground = #E3E3D8
TableHeader.separatorColor = #1A1C15
TableHeader.sortIconColor = #E3E3D8

Table.background = #1A1C15
Table.foreground = #E3E3D8
Table.selectionBackground = #33362E
Table.selectionForeground = #E3E3D8
Table.selectionInactiveBackground = #1E2019
Table.selectionInactiveForeground = #E3E3D8