#
# Setting system component properties
#
# This configuration is made for the FlatLaf layout system.
# For more information about this configuration you can consult the official documentation
# https://www.formdev.com/flatlaf/
#
# The official software documentation will be available later in this repository.
#
TitlePane.buttonSize = 48, 32
TitlePane.font = font:plain

Label.font = font:plain

Component.arc = 4
Component.borderWidth = 0
Component.focusWidth = 0

Button.arc = 6
Button.margin = 4, 6, 4, 6

TextComponent.arc = 4
TextField.margin = 4, 6, 4, 6

PasswordField.margin = 4, 6, 4, 6

FormattedTextField.margin = 4, 6, 4, 6

Spinner.padding = 4, 6, 4, 6

ComboBox.padding = 4, 6, 4, 6
ComboBox.borderCornerRadius = 4
ComboBox.selectionArc = 2

MenuItem.margin = 4, 6, 4, 6

TableHeader.height = 32
TableHeader.font = plain

Table.cellMargins = 4, 16, 4, 16

Table.rowHeight = 32

ScrollPane.arc = 8

ProgressBar.cycleTime = 1024