/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sansilvestre.desktop.app.launch.screens;

import com.formdev.flatlaf.FlatClientProperties;
import com.sansilvestre.desktop.app.launch.domain.util.Shift;

import java.time.LocalTime;

/**
 *
 * @author Jan
 */
public class LaunchScreen extends javax.swing.JPanel {

    private final Shift shift = new Shift();

    /**
     * Creates new form LaunchScreen
     */
    public LaunchScreen() {
        initComponents();
        initFlatLaf();
        scheduleInput.setSelectedItem(shift.getShift(LocalTime.now()));
    }

    private void initFlatLaf() {
        infoConteiner.putClientProperty(FlatClientProperties.STYLE, "arc:16;");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        bodyOneLabel = new javax.swing.JLabel();
        bodyTwoLabel = new javax.swing.JLabel();
        scheduleLabel = new javax.swing.JLabel();
        scheduleInput = new javax.swing.JComboBox<>();
        initEmployeePanel = new javax.swing.JButton();
        adminLabel = new javax.swing.JLabel();
        initAdminPanel = new javax.swing.JButton();
        infoPanel = new javax.swing.JPanel();
        infoConteiner = new javax.swing.JPanel();
        welcomeTitleLabel = new javax.swing.JLabel();
        welcomeBodyOneLabel = new javax.swing.JLabel();
        WelcomeBodyTwoLabel = new javax.swing.JLabel();
        utilTitleLabel = new javax.swing.JLabel();
        utilBodyOneLabel = new javax.swing.JLabel();
        utilBodyTwoLabel = new javax.swing.JLabel();
        utilBodyThreeLabel = new javax.swing.JLabel();
        helpTitleLabel = new javax.swing.JLabel();
        helpBodyOneLabel = new javax.swing.JLabel();
        helpBodyTwoLabel = new javax.swing.JLabel();
        helpBodyThreeLabel = new javax.swing.JLabel();
        helpBodyFourLabel = new javax.swing.JLabel();
        helpBodyFiveLabel = new javax.swing.JLabel();
        helpBodySixLabel = new javax.swing.JLabel();
        teamLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 238));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        initPanel.setBackground(new java.awt.Color(250, 250, 238));
        initPanel.setPreferredSize(new java.awt.Dimension(600, 700));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(26, 28, 21));
        titleLabel.setText("¿Qué tal el día?");

        bodyOneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bodyOneLabel.setForeground(new java.awt.Color(69, 72, 61));
        bodyOneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bodyOneLabel.setText("Verifica si el turno seleccionado es el correcto antes de ");

        bodyTwoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bodyTwoLabel.setForeground(new java.awt.Color(69, 72, 61));
        bodyTwoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bodyTwoLabel.setText("empezar tu turno");

        scheduleLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        scheduleLabel.setForeground(new java.awt.Color(26, 28, 21));
        scheduleLabel.setText("Turno");

        scheduleInput.setBackground(new java.awt.Color(227, 227, 216));
        scheduleInput.setEditable(true);
        scheduleInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        scheduleInput.setForeground(new java.awt.Color(26, 28, 21));
        scheduleInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turno 1 ~ 22:30 - 7:00", "Turno 2 ~ 7:00 - 14:00", "Turno 3 ~14:00 - 22:30" }));

        initEmployeePanel.setBackground(new java.awt.Color(79, 102, 40));
        initEmployeePanel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        initEmployeePanel.setForeground(new java.awt.Color(255, 255, 255));
        initEmployeePanel.setText("Comenzar");
        initEmployeePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initEmployeePanelActionPerformed(evt);
            }
        });

        adminLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminLabel.setForeground(new java.awt.Color(69, 72, 61));
        adminLabel.setText("¿Eres un administrador?");

        initAdminPanel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        initAdminPanel.setForeground(new java.awt.Color(79, 102, 40));
        initAdminPanel.setText("Ir al panel de administración");
        initAdminPanel.setContentAreaFilled(false);
        initAdminPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        initAdminPanel.setMargin(new java.awt.Insets(2, 4, 3, 14));
        initAdminPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initAdminPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout initPanelLayout = new javax.swing.GroupLayout(initPanel);
        initPanel.setLayout(initPanelLayout);
        initPanelLayout.setHorizontalGroup(
            initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initPanelLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(initPanelLayout.createSequentialGroup()
                        .addComponent(adminLabel)
                        .addGap(0, 0, 0)
                        .addComponent(initAdminPanel))
                    .addComponent(bodyOneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(initPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(initPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bodyTwoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scheduleLabel)
                    .addComponent(scheduleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(initEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        initPanelLayout.setVerticalGroup(
            initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initPanelLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(8, 8, 8)
                .addComponent(bodyOneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bodyTwoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(scheduleLabel)
                .addGap(8, 8, 8)
                .addComponent(scheduleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(initEmployeePanel)
                .addGap(128, 128, 128)
                .addGroup(initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(initAdminPanel))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        infoPanel.setBackground(new java.awt.Color(250, 250, 238));
        infoPanel.setPreferredSize(new java.awt.Dimension(600, 700));

        infoConteiner.setBackground(new java.awt.Color(221, 230, 198));

        welcomeTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeTitleLabel.setForeground(new java.awt.Color(23, 30, 10));
        welcomeTitleLabel.setText("Bienvenido a San Silvestre");

        welcomeBodyOneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        welcomeBodyOneLabel.setForeground(new java.awt.Color(23, 30, 10));
        welcomeBodyOneLabel.setText("Tenemos la herramienta perfecta para tu dia a dia en el local.");

        WelcomeBodyTwoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        WelcomeBodyTwoLabel.setForeground(new java.awt.Color(23, 30, 10));
        WelcomeBodyTwoLabel.setText("No te costara nada aprender a manejarla.");

        utilTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        utilTitleLabel.setForeground(new java.awt.Color(23, 30, 10));
        utilTitleLabel.setText("Sencillo pero util");

        utilBodyOneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        utilBodyOneLabel.setForeground(new java.awt.Color(23, 30, 10));
        utilBodyOneLabel.setText("Una interfaz sencilla, amigable y sobre todo útil. No te");

        utilBodyTwoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        utilBodyTwoLabel.setForeground(new java.awt.Color(23, 30, 10));
        utilBodyTwoLabel.setText("preocupes, solo debes atender a los clientes, el programa hará");

        utilBodyThreeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        utilBodyThreeLabel.setForeground(new java.awt.Color(23, 30, 10));
        utilBodyThreeLabel.setText("el resto por ti");

        helpTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        helpTitleLabel.setForeground(new java.awt.Color(23, 30, 10));
        helpTitleLabel.setText("Ayuda en todos lados");

        helpBodyOneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        helpBodyOneLabel.setForeground(new java.awt.Color(23, 30, 10));
        helpBodyOneLabel.setText("Si te sientes perdido o necesitas ayuda, siempre podrás ");

        helpBodyTwoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        helpBodyTwoLabel.setForeground(new java.awt.Color(23, 30, 10));
        helpBodyTwoLabel.setText("acceder a la pestaña de ayuda de cada sección del programa. ");

        helpBodyThreeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        helpBodyThreeLabel.setForeground(new java.awt.Color(23, 30, 10));
        helpBodyThreeLabel.setText("Allí encontraras preguntas frecuentes que se te puedan ");

        helpBodyFourLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        helpBodyFourLabel.setForeground(new java.awt.Color(23, 30, 10));
        helpBodyFourLabel.setText("ocurrir o atajos de teclado por si quieres agilizar tu trabajo.");

        helpBodyFiveLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        helpBodyFiveLabel.setForeground(new java.awt.Color(23, 30, 10));
        helpBodyFiveLabel.setText("Por cualquier otro inconveniente no dudes en contactar con ");

        helpBodySixLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        helpBodySixLabel.setForeground(new java.awt.Color(23, 30, 10));
        helpBodySixLabel.setText("los tus superiores.");

        teamLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        teamLabel.setForeground(new java.awt.Color(69, 72, 61));
        teamLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teamLabel.setText("Equipo de San Silvestre & Desarrollo");

        javax.swing.GroupLayout infoConteinerLayout = new javax.swing.GroupLayout(infoConteiner);
        infoConteiner.setLayout(infoConteinerLayout);
        infoConteinerLayout.setHorizontalGroup(
            infoConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoConteinerLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(infoConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helpTitleLabel)
                    .addComponent(utilTitleLabel)
                    .addGroup(infoConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(utilBodyOneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WelcomeBodyTwoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(welcomeBodyOneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(utilBodyTwoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                        .addComponent(helpBodyOneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(helpBodyTwoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(helpBodyThreeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(helpBodyFourLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(helpBodyFiveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(helpBodySixLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(teamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(welcomeTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(utilBodyThreeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        infoConteinerLayout.setVerticalGroup(
            infoConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoConteinerLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(welcomeTitleLabel)
                .addGap(8, 8, 8)
                .addComponent(welcomeBodyOneLabel)
                .addGap(0, 0, 0)
                .addComponent(WelcomeBodyTwoLabel)
                .addGap(24, 24, 24)
                .addComponent(utilTitleLabel)
                .addGap(0, 0, 0)
                .addComponent(utilBodyOneLabel)
                .addGap(0, 0, 0)
                .addComponent(utilBodyTwoLabel)
                .addGap(0, 0, 0)
                .addComponent(utilBodyThreeLabel)
                .addGap(24, 24, 24)
                .addComponent(helpTitleLabel)
                .addGap(0, 0, 0)
                .addComponent(helpBodyOneLabel)
                .addGap(0, 0, 0)
                .addComponent(helpBodyTwoLabel)
                .addGap(0, 0, 0)
                .addComponent(helpBodyThreeLabel)
                .addGap(0, 0, 0)
                .addComponent(helpBodyFourLabel)
                .addGap(24, 24, 24)
                .addComponent(helpBodyFiveLabel)
                .addGap(0, 0, 0)
                .addComponent(helpBodySixLabel)
                .addGap(64, 64, 64)
                .addComponent(teamLabel)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(infoConteiner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(infoConteiner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(initPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(initPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initEmployeePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initEmployeePanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initEmployeePanelActionPerformed

    private void initAdminPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initAdminPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initAdminPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WelcomeBodyTwoLabel;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JLabel bodyOneLabel;
    private javax.swing.JLabel bodyTwoLabel;
    private javax.swing.JLabel helpBodyFiveLabel;
    private javax.swing.JLabel helpBodyFourLabel;
    private javax.swing.JLabel helpBodyOneLabel;
    private javax.swing.JLabel helpBodySixLabel;
    private javax.swing.JLabel helpBodyThreeLabel;
    private javax.swing.JLabel helpBodyTwoLabel;
    private javax.swing.JLabel helpTitleLabel;
    private javax.swing.JPanel infoConteiner;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton initAdminPanel;
    private javax.swing.JButton initEmployeePanel;
    private javax.swing.JPanel initPanel;
    private javax.swing.JComboBox<String> scheduleInput;
    private javax.swing.JLabel scheduleLabel;
    private javax.swing.JLabel teamLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel utilBodyOneLabel;
    private javax.swing.JLabel utilBodyThreeLabel;
    private javax.swing.JLabel utilBodyTwoLabel;
    private javax.swing.JLabel utilTitleLabel;
    private javax.swing.JLabel welcomeBodyOneLabel;
    private javax.swing.JLabel welcomeTitleLabel;
    // End of variables declaration//GEN-END:variables
}
